services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - devnetwork
    ports:
      - "5249:5249"
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    restart: always
    ports:
      - "5000:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    networks:
      - devnetwork

networks:
  devnetwork:
    driver: bridge

volumes:
  seq_data:
